name: Verify

on:
  push:
    branches:
      - "**"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        working-directory: packages/react-component-breakpoints
        run: yarn build

      - name: Typecheck
        working-directory: packages/react-component-breakpoints
        run: yarn typecheck

      - name: Lint
        working-directory: packages/react-component-breakpoints
        run: yarn lint

      - name: Test
        working-directory: packages/react-component-breakpoints
        run: yarn test
